# Generated by Django 6.0.7 on 2026-07-26 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['date_added', 'text'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='learning_logs.topic'),
            preserve_default=False,
        ),
    ]
