# Generated by Django 6.0.7 on 2026-07-27 00:35

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
