# Generated by Django 6.0.7 on 2026-07-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_alter_entry_options_entry_title_entry_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='favorited',
            field=models.BooleanField(default=False),
        ),
    ]
